Main
greenbone/gvm-tools pull request #1097
Opened 2024-04-18 16:10 UTC by martinboller

## What

Additional and changed scripts for maintaining Greenbone and automating the creation of credentials, schedules, alerts, targets, tasks, tags and filters.

## Why

To automate the creation of a completely configured Greenbone Scanner

## References

Original gvm-tools scripts.

- [ ] Tests
[Install new scanner], alternatively
[clean-scanner]
[Prepare relevant CSV files for create-*.gmp.py scripts]
[create Credentials]
[Create Schedules
[Create Alerts]
[Create Targets]
[Create tasks}
[Create Tags]
[Create filters]
[List objects created w. list-*.gmp.py]
[Run task(s)]
[export-csv-report.gmp.py]
[export-pdf-report.gmp.py]
[Verify Reports]

2024-04-18 18:57 UTC, y0urself requested changes
Thank you for your contribution.
From what I see on the first view, you will probably need to run this with our CI tooling, because I expect these to fail (linting and formatting with `ruff` and `black`!).
I also noticed your copyright header, you may want to change these into our new format, that reduces the overhead in LoC for the header.

I will take another deep dive through your contribution tomorrow!

2024-04-18 18:57 UTC, y0urself commented on scripts/create-alerts-from-csv.gmp.py
> +    )
```suggestion
    print("Creating alerts.\n")
```

2024-04-18 18:57 UTC, y0urself commented on scripts/create-alerts-from-csv.gmp.py
> +# along with this program.  If not, see <http://www.gnu.org/licenses/>.
```suggestion
# SPDX-FileCopyrightText: 2024 Martin Boller
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Loosely based on Greenbone sample scripts
# As provided by Greenbone in the gvm-tools repo
```

2024-05-03 16:32 UTC, y0urself commented
@martinboller I would really love to merge this - is there any chance, that you fix up the stuff?

2024-05-03 18:06 UTC, martinboller commented
Will these changes satisfy requirements or am I missing something (or everything)

2024-05-27 07:11 UTC, y0urself commented
> Will these changes satisfy requirements or am I missing something (or everything)

No actually my suggestions were just examples, e.g. the Copyright header should have been updated in every file ...
Also running `black` and `ruff` in every file has not been done ...

2024-06-19 09:06 UTC, y0urself commented
merged through #1112

2024-06-19 09:06 UTC, closed without merging